// <auto-generated />
using MVCBasics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCBasics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCBasics.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            City = "Gothenburg",
                            Name = "Kalle Person",
                            PhoneNumber = "555-5555"
                        },
                        new
                        {
                            Id = "2",
                            City = "Gothenburg",
                            Name = "Stina Bratt",
                            PhoneNumber = "555-5555"
                        },
                        new
                        {
                            Id = "3",
                            City = "Paris",
                            Name = "Jennie Antonsson",
                            PhoneNumber = "444-4444"
                        },
                        new
                        {
                            Id = "4",
                            City = "London",
                            Name = "Sven Karlsson",
                            PhoneNumber = "888-8888"
                        },
                        new
                        {
                            Id = "5",
                            City = "Stockholm",
                            Name = "Katarina Fors",
                            PhoneNumber = "999-9999"
                        },
                        new
                        {
                            Id = "6",
                            City = "Warsaw",
                            Name = "Wendely Blom",
                            PhoneNumber = "222-2222"
                        },
                        new
                        {
                            Id = "7",
                            City = "Munich",
                            Name = "Hugo Magnusson",
                            PhoneNumber = "444-2222"
                        },
                        new
                        {
                            Id = "8",
                            City = "Bangkok",
                            Name = "Alice Olsson",
                            PhoneNumber = "111-1111"
                        },
                        new
                        {
                            Id = "9",
                            City = "Vladivostok",
                            Name = "Belly Button",
                            PhoneNumber = "000-4444"
                        },
                        new
                        {
                            Id = "10",
                            City = "Buenos Aires",
                            Name = "Tom Andersson",
                            PhoneNumber = "999-7777"
                        },
                        new
                        {
                            Id = "11",
                            City = "Hanoi",
                            Name = "Alma Starstruck",
                            PhoneNumber = "888-4444"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
